
CREATE TABLE IF NOT EXISTS "FuelConsumption" (
	"MODELYEAR"	INTEGER,
	"MAKE"	TEXT,
	"MODEL"	TEXT,
	"VEHICLECLASS"	TEXT,
	"ENGINESIZE"	INTEGER,
	"CYLINDERS"	INTEGER,
	"TRANSMISSION"	TEXT,
	"FUELTYPE"	TEXT,
	"FUELCONSUMPTION_CITY"	INTEGER,
	"FUELCONSUMPTION_HWY"	REAL,
	"FUELCONSUMPTION_COMB"	REAL,
	"FUELCONSUMPTION_COMB_MPG"	INTEGER,
	"CO2EMISSIONS"	INTEGER
);
